/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package babaie;

import com.formdev.flatlaf.FlatLightLaf;
import org.apache.pdfbox.pdmodel.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import java.io.FileOutputStream;



/**
 *
 * @author Notebook
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    String customerName;
    String barcode;
    String commodityName;
    String price;
    String number;
    String allprice;
    int range;
    long result;
    private List<Long> allprices;
    Connection c;
    Statement st;
    ResultSet rs;
    ResultSet rs1;
    ResultSet rs2;
    ResultSet rs3;
    ResultSet rs4;
    DefaultTableModel tblmodel;
    public Customer() {
        initComponents();
    }
    public Customer(String name) {
        initComponents();
        try {
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/babaiemarket" , "root" , "363831");
            st = c.createStatement();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Commoditys.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.tblmodel = (DefaultTableModel) customer_table.getModel();
        name_l.setText(name);
        allprices = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fName_t = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lName_t = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        result_t = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customer_table = new javax.swing.JTable();
        new_b = new javax.swing.JButton();
        add_b = new javax.swing.JButton();
        delete_b = new javax.swing.JButton();
        back_b = new javax.swing.JButton();
        name_l = new javax.swing.JLabel();
        result_l = new javax.swing.JLabel();
        edit_b = new javax.swing.JButton();
        new_l = new javax.swing.JLabel();
        add_l = new javax.swing.JLabel();
        edit_l = new javax.swing.JLabel();
        delete_l = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        print_b = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(34, 40, 49));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("نام : ");

        fName_t.setBackground(new java.awt.Color(255, 87, 34));
        fName_t.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fName_t.setForeground(new java.awt.Color(45, 64, 89));
        fName_t.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(34, 40, 49));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("نام خانوادگی :");

        lName_t.setBackground(new java.awt.Color(255, 87, 34));
        lName_t.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lName_t.setForeground(new java.awt.Color(45, 64, 89));
        lName_t.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lName_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lName_tActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(34, 40, 49));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("مجموع :");

        result_t.setBackground(new java.awt.Color(255, 87, 34));
        result_t.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        result_t.setForeground(new java.awt.Color(34, 40, 49));
        result_t.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(34, 40, 49));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("نام و نام خانوادگی :");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(34, 40, 49));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("مجموع :");

        customer_table.setBackground(new java.awt.Color(238, 238, 238));
        customer_table.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        customer_table.setForeground(new java.awt.Color(34, 40, 49));
        customer_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "کد کالا", "نام کالا", "قیمت", "تعداد", "قیمت کل"
            }
        ));
        customer_table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                customer_tableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(customer_table);

        new_b.setBackground(new java.awt.Color(255, 87, 34));
        new_b.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        new_b.setForeground(new java.awt.Color(45, 64, 89));
        new_b.setText("اضافه کردن سطر");
        new_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_bActionPerformed(evt);
            }
        });

        add_b.setBackground(new java.awt.Color(255, 87, 34));
        add_b.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        add_b.setForeground(new java.awt.Color(45, 64, 89));
        add_b.setText("ثبت محصول");
        add_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_bActionPerformed(evt);
            }
        });

        delete_b.setBackground(new java.awt.Color(255, 87, 34));
        delete_b.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        delete_b.setForeground(new java.awt.Color(45, 64, 89));
        delete_b.setText("حذف محصول");
        delete_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_bActionPerformed(evt);
            }
        });

        back_b.setBackground(new java.awt.Color(255, 87, 34));
        back_b.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        back_b.setForeground(new java.awt.Color(45, 64, 89));
        back_b.setText("برگشت");
        back_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_bActionPerformed(evt);
            }
        });

        name_l.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        name_l.setForeground(new java.awt.Color(34, 40, 49));
        name_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        result_l.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        result_l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        edit_b.setBackground(new java.awt.Color(255, 87, 34));
        edit_b.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        edit_b.setForeground(new java.awt.Color(45, 64, 89));
        edit_b.setText("تکمیل ویرایش");
        edit_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_bActionPerformed(evt);
            }
        });

        new_l.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        new_l.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        add_l.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        add_l.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        edit_l.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        edit_l.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        delete_l.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        delete_l.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel5.setText("jLabel5");

        print_b.setBackground(new java.awt.Color(255, 87, 34));
        print_b.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        print_b.setForeground(new java.awt.Color(45, 64, 89));
        print_b.setText("چاپ");
        print_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(result_l, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(name_l, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(back_b)
                        .addGap(18, 18, 18)
                        .addComponent(print_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(delete_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delete_b, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edit_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edit_b, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(add_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(add_b, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(new_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(new_b, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name_l, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(result_l, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(new_l, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_l, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit_l, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_l, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(delete_b, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(back_b, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(print_b, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(add_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(new_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edit_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            rs1 = st.executeQuery("SELECT COUNT(*) FROM `" + name_l.getText() + "`");
            if (rs1.next()) {
                range = rs1.getInt(1);
                String[][] values = new String[5*range][5];
                int num = 0;
                rs2 = st.executeQuery("SELECT * FROM `" + name_l.getText() + "`");
                while (num<5*range && rs2.next()) {
                    values[num][0] = rs2.getString("barcode");
                    values[num][1] = rs2.getString("commodityname");
                    values[num][2] = rs2.getString("price");
                    values[num][3] = rs2.getString("number");
                    values[num][4] = rs2.getString("allprice");
                    num++;
                }
                rs3 = st.executeQuery("SELECT * FROM customers WHERE customername LIKE '" + name_l.getText() + "'");
                if (rs3.next()) {
                    result = Long.parseLong(rs3.getString("result"));
                    result_l.setText(result + "");
                }
                // make rows in java table
                for (int i = 0 ; i<range ; i++) {
                    tblmodel.addRow(values[i]);
                }   
            }
        } catch (SQLException ex) {
            Logger.getLogger(Commoditys.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void lName_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lName_tActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lName_tActionPerformed

    private void customer_tableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customer_tableKeyPressed
        // TODO add your handling code here:
        int row = customer_table.getSelectedRow();
        long allprice;
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && customer_table.getSelectedColumn() == 0) {
            if (!customer_table.getValueAt(row, 0).equals(null)) {
                try {
                    rs = st.executeQuery("SELECT * FROM commodity WHERE barcode LIKE '" + customer_table.getValueAt(row, 0) + "'");
                    while (rs.next()) {
                        customer_table.setValueAt(rs.getString("commodityname"), row, 1);
                        customer_table.setValueAt(rs.getString("sales"), row, 2);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!customer_table.getValueAt(row, 2).equals(null) && !customer_table.getValueAt(row, 3).equals(null)){
                allprice = Long.parseLong((String) customer_table.getValueAt(row, 2)) * Long.parseLong((String) customer_table.getValueAt(row, 3));
                customer_table.setValueAt(allprice + "", row, 4);
            }
        }
    }//GEN-LAST:event_customer_tableKeyPressed

    private void new_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_bActionPerformed
        // TODO add your handling code here:
        tblmodel.addRow(new Object[]{"کد کالا", "نام کالا" , "0" , "0", "0"});
        new_l.setText("سطر جدید اضافه شد");
        Timer t = new Timer (3000 , new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new_l.setText("");
            }
        });
        t.start();

    }//GEN-LAST:event_new_bActionPerformed

    private void add_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_bActionPerformed
        try {
            // TODO add your handling code here:
            int row = customer_table.getSelectedRow();
            int rowCount = tblmodel.getRowCount();
            barcode = (String) customer_table.getValueAt(row, 0);
            commodityName = (String) customer_table.getValueAt(row, 1);
            price = (String) customer_table.getValueAt(row, 2);
            number = (String) customer_table.getValueAt(row, 3);
            allprice = (String) customer_table.getValueAt(row, 4);
            result = 0;
            allprices.removeAll(allprices);
            for (int i =0; i<rowCount; i++) {
                allprices.add(Long.parseLong((String) customer_table.getValueAt(i, 4)));
            }
            for (long allPrice : allprices) {
                result = result + allPrice;
            }
            result_l.setText(result + "");
            st.executeUpdate("INSERT INTO `" + name_l.getText() + "` (barcode,commodityname,price,number,allprice) VALUES ('" + barcode + "','" + commodityName + "','" + price + "','" + number + "','" + allprice + "')");
            st.executeUpdate("SET @count = 0;");
            st.executeUpdate("UPDATE `" + name_l.getText() + "` SET id = @count:= @count + 1;");
            st.executeUpdate("UPDATE customers SET result = '" + result + "' WHERE customername LIKE '" + name_l.getText() + "'");
            add_l.setText("کالا اضافه شد");
            Timer t = new Timer (3000 , new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    add_l.setText("");
                }
            });
            t.start();
        } catch (SQLException ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_add_bActionPerformed

    private void delete_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_bActionPerformed
        try {
            // TODO add your handling code here:
            int row = customer_table.getSelectedRow();
            allprice = (String) customer_table.getValueAt(row, 4);
            barcode = (String) customer_table.getValueAt(row, 0);
            result = 0;
            allprices.removeAll(allprices);
            
            st.executeUpdate("DELETE FROM `" + name_l.getText()  + "` WHERE id LIKE '" + (row+1) + "';");
            
            st.executeUpdate("SET @count = 0;");
            st.executeUpdate("UPDATE `" + name_l.getText() + "` SET id = @count:= @count + 1;");
            
            tblmodel.removeRow(row);
            int rowCount = tblmodel.getRowCount();
            for (int i =0; i<rowCount; i++) {
                allprices.add(Long.parseLong((String) customer_table.getValueAt(i, 4)));
            }
            for (long allPrice : allprices) {
                result = result + allPrice;
            }
            result_l.setText(result + "");
            st.executeUpdate("UPDATE customers SET result = '" + result + "' WHERE customername LIKE '" + name_l.getText() + "'");
            delete_l.setText("حذف شد");
            Timer t = new Timer (3000 , new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    delete_l.setText("");
                }
            });
            t.start();
        } catch (SQLException ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_delete_bActionPerformed

    private void back_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_bActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_back_bActionPerformed

    private void edit_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_bActionPerformed
        try {
            // TODO add your handling code here:
            int row = customer_table.getSelectedRow();
            int rowCount = tblmodel.getRowCount();
            barcode = (String) customer_table.getValueAt(row, 0);
            commodityName = (String) customer_table.getValueAt(row, 1);
            price = (String) customer_table.getValueAt(row, 2);
            number = (String) customer_table.getValueAt(row, 3);
            allprice = (String) customer_table.getValueAt(row, 4);
            result = 0;
            allprices.removeAll(allprices);
            for (int i =0; i<rowCount; i++) {
                allprices.add(Long.parseLong((String) customer_table.getValueAt(i, 4)));
            }
            for (long allPrice : allprices) {
                result = result + allPrice;
            }
            result_l.setText(result + "");
            st.executeUpdate("UPDATE `" + name_l.getText() + "` SET  commodityname = '" + commodityName + "', price = '" + price + "', number = '" + number + "', allprice = '" + allprice + "' WHERE barcode = '" + barcode + "';" );
            st.executeUpdate("UPDATE customers SET result = '" + result + "' WHERE customername LIKE '" + name_l.getText() + "'");
            edit_l.setText("ویرایش شد ");
            Timer t = new Timer (3000 , new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    edit_l.setText("");
                }
            });
            t.start();
        } catch (SQLException ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_edit_bActionPerformed

    private void print_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_bActionPerformed
        // TODO add your handling code here:
        Document document = new Document(PageSize.A4, 50, 50, 50, 50);

        try {
            // Create a PdfWriter instance
            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("output.pdf"));
            // Open the document
            document.open();

            // Create a PdfPTable with 3 columns
            PdfPTable table = new PdfPTable(3);

            // Add table headers
            table.addCell("کد کالا");
            table.addCell("نام کالا");
            table.addCell("قیمت");
            table.addCell("تعداد");
            table.addCell("قیمت کل");

            // Populate the table with data
            for (int row = 1; row <= 5; row++) {
                for (int col = 1; col <= 3; col++) {
                    table.addCell("سطر " + row + ", ستون " + col);
                }
            }

            // Set the font of the table to an Arabic font
            
            Paragraph paragraph = new Paragraph("هذا نص عربي");
            document.add(paragraph);
            // Add the table to the document

            // Close the document
            document.close();

            System.out.println("PDF created successfully!");
        } catch (DocumentException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_print_bActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatLightLaf.setup();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_b;
    private javax.swing.JLabel add_l;
    private javax.swing.JButton back_b;
    private javax.swing.JTable customer_table;
    private javax.swing.JButton delete_b;
    private javax.swing.JLabel delete_l;
    private javax.swing.JButton edit_b;
    private javax.swing.JLabel edit_l;
    private javax.swing.JTextField fName_t;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lName_t;
    private javax.swing.JLabel name_l;
    private javax.swing.JButton new_b;
    private javax.swing.JLabel new_l;
    private javax.swing.JButton print_b;
    private javax.swing.JLabel result_l;
    private javax.swing.JTextField result_t;
    // End of variables declaration//GEN-END:variables
}
