/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package babaie;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.Timer;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Notebook
 */
public class NewCustomer extends javax.swing.JFrame {

    /**
     * Creates new form NewCustomer
     */
    long result;
    private List<Long> allprices;
    String customerName;
    Connection c;
    Statement st;
    ResultSet rs;
    DefaultTableModel tblmodel;
    public NewCustomer() {
        initComponents();
        allprices = new ArrayList<>();
        try {
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/babaiemarket" , "root" , "363831");
            st = c.createStatement();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Commoditys.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.tblmodel = (DefaultTableModel) customer_table.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fName_t = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lName_t = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        customer_table = new javax.swing.JTable();
        new_b = new javax.swing.JButton();
        add_b = new javax.swing.JButton();
        delete_b = new javax.swing.JButton();
        back_b = new javax.swing.JButton();
        new_l = new javax.swing.JLabel();
        add_l = new javax.swing.JLabel();
        delete_l = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        result_t = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(238, 238, 238));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(34, 40, 49));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("نام : ");

        fName_t.setBackground(new java.awt.Color(255, 87, 34));
        fName_t.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        fName_t.setForeground(new java.awt.Color(45, 64, 89));
        fName_t.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(34, 40, 49));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("نام خانوادگی :");

        lName_t.setBackground(new java.awt.Color(255, 87, 34));
        lName_t.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lName_t.setForeground(new java.awt.Color(45, 64, 89));
        lName_t.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lName_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lName_tActionPerformed(evt);
            }
        });

        customer_table.setBackground(new java.awt.Color(238, 238, 238));
        customer_table.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        customer_table.setForeground(new java.awt.Color(34, 40, 49));
        customer_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "کد کالا", "نام کالا", "قیمت", "تعداد", "قیمت کل"
            }
        ));
        customer_table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                customer_tableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(customer_table);

        new_b.setBackground(new java.awt.Color(255, 87, 34));
        new_b.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        new_b.setForeground(new java.awt.Color(45, 64, 89));
        new_b.setText("اضافه کردن سطر");
        new_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_bActionPerformed(evt);
            }
        });

        add_b.setBackground(new java.awt.Color(255, 87, 34));
        add_b.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        add_b.setForeground(new java.awt.Color(45, 64, 89));
        add_b.setText("ثبت مشتری");
        add_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_bActionPerformed(evt);
            }
        });

        delete_b.setBackground(new java.awt.Color(255, 87, 34));
        delete_b.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        delete_b.setForeground(new java.awt.Color(45, 64, 89));
        delete_b.setText("حذف سطر");
        delete_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_bActionPerformed(evt);
            }
        });

        back_b.setBackground(new java.awt.Color(255, 87, 34));
        back_b.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        back_b.setForeground(new java.awt.Color(45, 64, 89));
        back_b.setText("برگشت");
        back_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_bActionPerformed(evt);
            }
        });

        new_l.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        new_l.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        add_l.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        add_l.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        delete_l.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        delete_l.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(34, 40, 49));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("مجموع :");

        result_t.setBackground(new java.awt.Color(255, 87, 34));
        result_t.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        result_t.setForeground(new java.awt.Color(34, 40, 49));
        result_t.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 44, Short.MAX_VALUE)
                        .addComponent(result_t, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lName_t, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(fName_t, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(back_b, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(delete_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delete_b, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(add_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(add_b, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(new_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(new_b, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lName_t, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fName_t, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(result_t, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(new_l, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_l, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_l, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(new_b, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(add_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(back_b, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete_b, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lName_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lName_tActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lName_tActionPerformed

    private void new_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_bActionPerformed
        // TODO add your handling code here:
        tblmodel.addRow(new Object[]{"کد کالا", "نام کالا" , "0" , "0", "0"});
        new_l.setText("سطر جدید اضافه شد");
        Timer t = new Timer (3000 , new ActionListener() {
            @Override
                public void actionPerformed(ActionEvent e) {
                    new_l.setText("");
                }
            });
        t.start();
        
    }//GEN-LAST:event_new_bActionPerformed

    private void back_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_bActionPerformed
        // TODO add your handling code here:
        Main m = new Main();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_bActionPerformed

    private void add_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_bActionPerformed
        // TODO add your handling code here:
        customerName = fName_t.getText() + " " + lName_t.getText();
        int rowCount = customer_table.getRowCount();
        String[][]values = new String[rowCount][5];
        allprices.removeAll(allprices);
        result = 0;
        for (int i = 0; i<rowCount; i++) {
            for (int j = 0; j<5; j++) {
                values[i][j] = (String) customer_table.getValueAt(i, j);
            }
            allprices.add(Long.parseLong((String) customer_table.getValueAt(i, 4)));
        }
        try {
            st.executeUpdate("CREATE TABLE `" + customerName + "` (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, barcode VARCHAR(32) NOT NULL, commodityname VARCHAR(32) NOT NULL, price VARCHAR(32) NOT NULL, number VARCHAR(32) NOT NULL, allprice VARCHAR(32) NOT NULL);");
            for (int i = 0; i<rowCount; i++) {
                st.executeUpdate("INSERT INTO `" + customerName + "` (barcode,commodityname,price,number,allprice) VALUES ('" + values[i][0] + "','" + values[i][1] + "','" + values[i][2] + "','" + values[i][3] + "','" + values[i][4] + "');");
            }
            for (long allPrice : allprices) {
                result = result + allPrice;
            }
            result_t.setText(result + "");
            st.executeUpdate("INSERT INTO customers VALUES('" + customerName + "','" + result + "')");
        } catch (SQLException ex) {
            Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        add_l.setText("مشتری اضافه شد");
        Timer t = new Timer (3000 , new ActionListener() {
            @Override
                public void actionPerformed(ActionEvent e) {
                    add_l.setText("");
                }
            });
        t.start();
    }//GEN-LAST:event_add_bActionPerformed

    private void delete_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_bActionPerformed
        // TODO add your handling code here:
        int row = customer_table.getSelectedRow();
        int rowCount = tblmodel.getRowCount();
        allprices.removeAll(allprices);
        for (int i =0; i<rowCount; i++) {
            allprices.add(Long.parseLong((String) customer_table.getValueAt(i, 4)));
        }
        allprices.remove(row);
        result = 0;
        for (long allPrice : allprices) {
            result = result + allPrice;
        }
        result_t.setText(result + "");
        try {
            st.executeUpdate("UPDATE customers SET result = '" + result + "' WHERE customername LIKE '" + customerName + "'");
        } catch (SQLException ex) {
            Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblmodel.removeRow(row);
        delete_l.setText("حذف شد");
        Timer t = new Timer (3000 , new ActionListener() {
            @Override
                public void actionPerformed(ActionEvent e) {
                    delete_l.setText("");
                }
            });
        t.start();
    }//GEN-LAST:event_delete_bActionPerformed

    private void customer_tableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customer_tableKeyPressed
        // TODO add your handling code here:
        int row = customer_table.getSelectedRow();
        int allprice;
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!customer_table.getValueAt(row, 0).equals(null)) {
                try {
                    rs = st.executeQuery("SELECT * FROM commodity WHERE barcode LIKE '" + customer_table.getValueAt(row, 0) + "'");
                    while (rs.next()) {
                        customer_table.setValueAt(rs.getString("commodityname"), row, 1);
                        customer_table.setValueAt(rs.getString("sales"), row, 2);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(NewCustomer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
            if (!customer_table.getValueAt(row, 2).equals(null) && !customer_table.getValueAt(row, 3).equals(null)){
                allprice = Integer.parseInt((String) customer_table.getValueAt(row, 2)) * Integer.parseInt((String) customer_table.getValueAt(row, 3));
                customer_table.setValueAt(allprice + "", row, 4);
            }
        }
    }//GEN-LAST:event_customer_tableKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_b;
    private javax.swing.JLabel add_l;
    private javax.swing.JButton back_b;
    private javax.swing.JTable customer_table;
    private javax.swing.JButton delete_b;
    private javax.swing.JLabel delete_l;
    private javax.swing.JTextField fName_t;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lName_t;
    private javax.swing.JButton new_b;
    private javax.swing.JLabel new_l;
    private javax.swing.JTextField result_t;
    // End of variables declaration//GEN-END:variables
}
