/////////////////////////////////////////////////////////////////morteza mahdi zadeh
/////////////////////////////////////////////////////////////////4012023030
import com.formdev.flatlaf.FlatLightLaf;
import com.mysql.cj.jdbc.DatabaseMetaData;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

public class Inbox extends javax.swing.JFrame{

/**
     * Creates new form Inbox
     */
        public Inbox() {
        initComponents();
    }

    
    public Inbox(String signUpEmail) {
    
        initComponents();
        accountName_l.setText(signUpEmail);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        label1 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        email_table = new javax.swing.JTable();
        send_b = new javax.swing.JButton();
        important_b = new javax.swing.JButton();
        changeAccount_b = new javax.swing.JButton();
        sent_b = new javax.swing.JButton();
        see_b = new javax.swing.JButton();
        seeError_l = new javax.swing.JLabel();
        remove_b = new javax.swing.JButton();
        removeError_l = new javax.swing.JLabel();
        accountName_l = new javax.swing.JLabel();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                showMessages(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(229, 229, 229));

        jPanel3.setBackground(new java.awt.Color(252, 163, 17));

        email_table.setAutoCreateRowSorter(true);
        email_table.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        email_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "From/To", "Subject", "Date&Time", "Read/UnRead"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        email_table.setRowHeight(30);
        email_table.setSelectionForeground(new java.awt.Color(0, 0, 0));
        email_table.setShowGrid(false);
        jScrollPane1.setViewportView(email_table);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                .addContainerGap())
        );

        send_b.setBackground(new java.awt.Color(255, 255, 255));
        send_b.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        send_b.setText("Send");
        send_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_bActionPerformed(evt);
            }
        });

        important_b.setBackground(new java.awt.Color(255, 255, 255));
        important_b.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        important_b.setText("Important");
        important_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                important_bActionPerformed(evt);
            }
        });

        changeAccount_b.setBackground(new java.awt.Color(255, 255, 255));
        changeAccount_b.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        changeAccount_b.setText("Change Account");
        changeAccount_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeAccount_bActionPerformed(evt);
            }
        });

        sent_b.setBackground(new java.awt.Color(255, 255, 255));
        sent_b.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        sent_b.setText("Sent");
        sent_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sent_bActionPerformed(evt);
            }
        });

        see_b.setBackground(new java.awt.Color(255, 255, 255));
        see_b.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        see_b.setText("See");
        see_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                see_bActionPerformed(evt);
            }
        });

        seeError_l.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        seeError_l.setForeground(new java.awt.Color(230, 55, 69));

        remove_b.setBackground(new java.awt.Color(255, 255, 255));
        remove_b.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        remove_b.setText("Remove");
        remove_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_bActionPerformed(evt);
            }
        });

        removeError_l.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        removeError_l.setForeground(new java.awt.Color(230, 55, 69));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(important_b, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(sent_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(send_b, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(see_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changeAccount_b, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(seeError_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(remove_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeError_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(send_b, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sent_b, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(important_b, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(changeAccount_b, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seeError_l, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(see_b, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(removeError_l, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(remove_b, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        accountName_l.setBackground(new java.awt.Color(255, 255, 255));
        accountName_l.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        accountName_l.setForeground(new java.awt.Color(252, 163, 17));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountName_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountName_l, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeAccount_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeAccount_bActionPerformed
        Signup su = new Signup();
         su.setVisible(true);
        dispose();
    }//GEN-LAST:event_changeAccount_bActionPerformed

    private void send_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_bActionPerformed
        String emailName = accountName_l.getText();
        Send s = new Send(emailName);
        s.setVisible(true);
        
    }//GEN-LAST:event_send_bActionPerformed

    private void showMessages(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_showMessages
        
    }//GEN-LAST:event_showMessages

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //create an object for the table
        DefaultTableModel tblmodel1 = (DefaultTableModel) email_table.getModel();
        TableColumnModel columnModel = email_table.getColumnModel();
        String user = accountName_l.getText().substring(0, accountName_l.getText().indexOf('@'));
        int range = 0;
        Connection c;
        try {
            // an object for connect to sql
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/emails" , "root" , "363831");
            Statement st = c.createStatement();
                // take count of rows in user sql table
            ResultSet rs2 = st.executeQuery("SELECT COUNT(*) FROM " + user);
            if (rs2.next()) {
                range = rs2.getInt(1);
            }
                
            String[][] values2 = new String[4*range][4];
            int num1 = 0;
            // take records in each row
            ResultSet rs = st.executeQuery("SELECT * FROM " + user);
               
            while (num1<4*range && rs.next()) {
                values2[num1][0] = rs.getString("sender");
                values2[num1][1] = rs.getString("subject");
                values2[num1][2] = rs.getString("date");
                values2[num1][3] = rs.getString("read_unread");
            num1++;

            }
            
            // make rows in java table
            for (int i = 0 ; i<range ; i++) {
                tblmodel1.addRow(values2[i]);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Sent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void important_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_important_bActionPerformed
        // TODO add your handling code here:
        Important i = new Important(accountName_l.getText());
        i.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_important_bActionPerformed

    private void see_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_see_bActionPerformed
        // TODO add your handling code here:
        
        // create an object for table
        DefaultTableModel tblmodel = (DefaultTableModel) email_table.getModel();
        String user = accountName_l.getText().substring(0, accountName_l.getText().indexOf('@'));
        int row = email_table.getSelectedRow();
        Connection c;
        try {
            // connect to sql
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/emails" , "root" , "363831");
            Statement st = c.createStatement();
            DatabaseMetaData dbm = (DatabaseMetaData) c.getMetaData();
            // is exist this table or no !?
            ResultSet tables = dbm.getTables(null, null, user, null);
            if (tables.next()){
                if (row == -1) {
                    seeError_l.setText("please selecet a row !");
                    Timer t = new Timer (1000 , new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            seeError_l.setText("");
                        }
                    });
                    t.start();
                } 
                else {
                    seeError_l.setText("");
                    // recieve values from java table in a special row
                    String from = (String) tblmodel.getValueAt(row, 0);
                    String subject = (String) tblmodel.getValueAt(row, 1);
                    String date = (String) tblmodel.getValueAt(row, 2);
                    String message = null;
                    // recieve message record from sql table
                    ResultSet rs = st.executeQuery("SELECT * FROM " + user + " WHERE sender = '" + from + "' AND subject = '" + subject + "' AND date = '" + date + "'");
                    // save this record on string message
                    if (rs.next()) {
                        message = rs.getString("message");
                    }
                    st.executeUpdate("UPDATE " + user + " SET read_unread = 'read' WHERE sender = '" + from + "' AND subject = '" + subject + "' AND date = '" + date + "'");
                    tblmodel.setValueAt("read", row, 3);
                    // make an object for class see and set it visible
                    See s = new See(from , subject , message , accountName_l.getText());
                    s.setVisible(true);
                    tblmodel.setValueAt("Read", row, 3);
                }
                
            }
            else {
                seeError_l.setText("please selecet a row !");
                Timer t = new Timer (1000 , new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            seeError_l.setText("");
                        }
                    });
                t.start();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Sent.class.getName()).log(Level.SEVERE, null, ex);
        }
             
        
    }//GEN-LAST:event_see_bActionPerformed

    private void sent_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sent_bActionPerformed
        // TODO add your handling code here:
        Sent s = new Sent(accountName_l.getText());
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_sent_bActionPerformed

    private void remove_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_bActionPerformed
        // TODO add your handling code here:
        
        String user = accountName_l.getText().substring(0, accountName_l.getText().indexOf('@'));
        DefaultTableModel tblmodel = (DefaultTableModel) email_table.getModel();
        int row = email_table.getSelectedRow();
        
        Connection c;
        try {
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/emails" , "root" , "363831");
            Statement st = c.createStatement();
            DatabaseMetaData dbm = (DatabaseMetaData) c.getMetaData();
            ResultSet tables = dbm.getTables(null, null, user, null);
            if (tables.next()) {
                if (row == -1) {
                    removeError_l.setText("please selecet a row !");
                    Timer t = new Timer (1000 , new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            removeError_l.setText("");
                        }
                    }); 
                    t.start();
                }
                else {
                    removeError_l.setText("");
                    String value1 = tblmodel.getValueAt(row, 0).toString();
                    String value2 = tblmodel.getValueAt(row, 1).toString();
                    String value3 = tblmodel.getValueAt(row, 2).toString();
                    // remmove selected row from sql table
                    st.executeUpdate("DELETE FROM " + user + " WHERE sender LIKE '" + value1 + "' AND subject LIKE '" + value2 + "' AND date LIKE '" + value3 + "'");
                    // remove selected row from java table
                    tblmodel.removeRow(row);
                }
            }
            else {
                removeError_l.setText("please selecet a row !");
                Timer t = new Timer (1000 , new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            removeError_l.setText("");
                            }
                    });
                t.start();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Sent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_remove_bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountName_l;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton changeAccount_b;
    private javax.swing.JTable email_table;
    private javax.swing.JButton important_b;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JLabel removeError_l;
    private javax.swing.JButton remove_b;
    private javax.swing.JLabel seeError_l;
    private javax.swing.JButton see_b;
    private javax.swing.JButton send_b;
    private javax.swing.JButton sent_b;
    // End of variables declaration//GEN-END:variables
}
