/////////////////////////////////////////////////////////////////morteza mahdi zadeh
/////////////////////////////////////////////////////////////////4012023030
import com.mysql.cj.jdbc.Driver;
import java.sql.*;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Notebook
 */
public class See extends javax.swing.JFrame {

    /**
     * Creates new form See
     */
    public See() {
        initComponents();
    }
    
    public See(String from ,String subject ,String message ,String accountName) {
        // show selected email to user
        initComponents();
        accountName_l.setText(accountName);
        String f = from;
        String s = subject;
        String m = message;
        from_ta.setText(f);
        subject_ta.setText(s);
        message_ta.setText(m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ok_b = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        from_ta = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        subject_ta = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        message_ta = new javax.swing.JTextArea();
        toImportant_b = new javax.swing.JButton();
        accountName_l = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(229, 229, 229));

        ok_b.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        ok_b.setText("Ok");
        ok_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_bActionPerformed(evt);
            }
        });

        from_ta.setBackground(new java.awt.Color(252, 163, 17));
        from_ta.setColumns(20);
        from_ta.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        from_ta.setForeground(new java.awt.Color(20, 33, 61));
        from_ta.setRows(1);
        jScrollPane1.setViewportView(from_ta);

        subject_ta.setBackground(new java.awt.Color(252, 163, 17));
        subject_ta.setColumns(20);
        subject_ta.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        subject_ta.setForeground(new java.awt.Color(20, 33, 61));
        subject_ta.setRows(1);
        jScrollPane2.setViewportView(subject_ta);

        message_ta.setBackground(new java.awt.Color(252, 163, 17));
        message_ta.setColumns(20);
        message_ta.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        message_ta.setForeground(new java.awt.Color(20, 33, 61));
        message_ta.setRows(5);
        jScrollPane3.setViewportView(message_ta);

        toImportant_b.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        toImportant_b.setText("To Important");
        toImportant_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toImportant_bActionPerformed(evt);
            }
        });

        accountName_l.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ok_b, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(toImportant_b, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(accountName_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountName_l, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ok_b, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(toImportant_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ok_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_bActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ok_bActionPerformed

    private void toImportant_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toImportant_bActionPerformed
        // TODO add your handling code here:
        // records values in sql important_user table
        String user = accountName_l.getText().substring(0, accountName_l.getText().indexOf('@'));
        String from = from_ta.getText();
        String subject = subject_ta.getText();
        String message = message_ta.getText();
        try {
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/emails" , "root" , "363831");
            Statement st = c.createStatement();
            st.executeUpdate("INSERT INTO important_" + user + " (subject,sender,message)" + " VALUES ('" + subject + "','" + from + "','" + message + "')");
        } catch (SQLException ex) {
            Logger.getLogger(See.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_toImportant_bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(See.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(See.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(See.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(See.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new See().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountName_l;
    private javax.swing.JTextArea from_ta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea message_ta;
    private javax.swing.JButton ok_b;
    private javax.swing.JTextArea subject_ta;
    private javax.swing.JButton toImportant_b;
    // End of variables declaration//GEN-END:variables
}
