/////////////////////////////////////////////////////////////////morteza mahdi zadeh
/////////////////////////////////////////////////////////////////4012023030
import com.mysql.cj.jdbc.Driver;
import java.sql.*;
import com.formdev.flatlaf.FlatLightLaf;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date;
import java.text.SimpleDateFormat;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Notebook
 */
public class Send extends javax.swing.JFrame {

    /**
     * Creates new form Send
     */
    public Send() {
        initComponents();
    }
    // define some strings
        String fromEmail;
        String toEmail;
        String subject;
        String message;
    public Send(String emailName) {
        initComponents();
        from_l.setText(emailName);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        toEmail_t = new javax.swing.JTextField();
        subject_t = new javax.swing.JTextField();
        message_t = new javax.swing.JTextField();
        send_b = new javax.swing.JButton();
        clear_b = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        from_l = new javax.swing.JLabel();
        toEmailError_l = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 300));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(229, 229, 229));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(20, 33, 61));
        jLabel1.setText("TO :");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(20, 33, 61));
        jLabel2.setText("SUBJECT :");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(20, 33, 61));
        jLabel3.setText("MESSAGE :");

        toEmail_t.setBackground(new java.awt.Color(252, 163, 17));
        toEmail_t.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        toEmail_t.setToolTipText("LIKE : abc123@future.com");

        subject_t.setBackground(new java.awt.Color(252, 163, 17));
        subject_t.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        subject_t.setToolTipText("WRITE A SUBJECT HERE");

        message_t.setBackground(new java.awt.Color(252, 163, 17));
        message_t.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        message_t.setToolTipText("WRITE A MESSAGE HERE");

        send_b.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        send_b.setText("Send");
        send_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_bActionPerformed(evt);
            }
        });

        clear_b.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        clear_b.setText("Clear");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(20, 33, 61));
        jLabel4.setText("FROM :");

        from_l.setBackground(new java.awt.Color(241, 250, 239));
        from_l.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        from_l.setForeground(new java.awt.Color(29, 53, 87));

        toEmailError_l.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        toEmailError_l.setForeground(new java.awt.Color(230, 55, 69));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel4))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(send_b, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(clear_b, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(subject_t)
                    .addComponent(message_t)
                    .addComponent(toEmail_t)
                    .addComponent(from_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toEmailError_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(from_l))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(toEmailError_l, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toEmail_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subject_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(message_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear_b, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(send_b, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void send_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_bActionPerformed
        try {    
            //create object for date
            Date date = new Date();
            SimpleDateFormat simpleDate = new SimpleDateFormat("MM/dd hh:mm a");
            // give some values for strings
            fromEmail = from_l.getText();
            toEmail = toEmail_t.getText();
            subject = subject_t.getText();
            message = message_t.getText();
            String user = toEmail.substring(0, toEmail.indexOf('@'));
            String user2 = fromEmail.substring(0, fromEmail.indexOf('@'));
            // create object for con and st
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/emails" , "root" , "363831");
            Statement st = c.createStatement();
            //query for check is there exists the table or no 
            ResultSet rs = st.executeQuery("  SELECT *FROM information_schema.tables WHERE table_schema = 'emails' AND table_name = '" + user + "'");
            System.out.println("adsfdsfd");
            
            if (rs.next()){
                // save records with query in toEmail table
                st.executeUpdate("INSERT INTO " + user + "(subject,message,sender,date,read_unread) VALUES ('" + subject + "','" + message + "','" + fromEmail + "','" + simpleDate.format(date) + "','unread')");
                // save records with query in sented_fromEmail table
                st.executeUpdate("INSERT INTO sented_" + user2 + "(subject,message,sender,date) VALUES ('" + subject + "','" + message + "','" + fromEmail + "','" + simpleDate.format(date) + "')");
                dispose();
            }
            else {
                toEmailError_l.setText("enter correct email please !");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Send.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_send_bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatLightLaf.setup();

// create UI here...
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Send().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear_b;
    private javax.swing.JLabel from_l;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField message_t;
    private javax.swing.JButton send_b;
    private javax.swing.JTextField subject_t;
    private javax.swing.JLabel toEmailError_l;
    private javax.swing.JTextField toEmail_t;
    // End of variables declaration//GEN-END:variables
}
