/////////////////////////////////////////////////////////////////morteza mahdi zadeh
/////////////////////////////////////////////////////////////////4012023030
import com.mysql.cj.jdbc.Driver;
import java.sql.*;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Signin extends javax.swing.JFrame {

    // make some string for inputs
    String fName;
    String lName;
    String Email;
    String Password;
    
    public Signin() {
        initComponents();
        fName = fName_t.getText();
        lName = lName_t.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        signIn_l = new javax.swing.JLabel();
        back_b = new javax.swing.JButton();
        fName_t = new javax.swing.JTextField();
        lName_t = new javax.swing.JTextField();
        email_t = new javax.swing.JTextField();
        fName_l = new javax.swing.JLabel();
        lName_l = new javax.swing.JLabel();
        email_l = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        password_t = new javax.swing.JPasswordField();
        emailError_l = new javax.swing.JLabel();
        fnameError_l = new javax.swing.JLabel();
        lnameError_l = new javax.swing.JLabel();
        passwordError_l = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(229, 229, 229));
        jPanel1.setForeground(new java.awt.Color(230, 55, 69));

        signIn_l.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        signIn_l.setForeground(new java.awt.Color(20, 33, 61));
        signIn_l.setText("SIGN IN");

        back_b.setBackground(new java.awt.Color(167, 218, 220));
        back_b.setIcon(new javax.swing.ImageIcon("C:\\Users\\Notebook\\OneDrive\\Documents\\NetBeansProjects\\Gmail\\back.png")); // NOI18N
        back_b.setContentAreaFilled(false);
        back_b.setPreferredSize(new java.awt.Dimension(50, 50));
        back_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_bActionPerformed(evt);
            }
        });

        fName_t.setBackground(new java.awt.Color(252, 163, 17));
        fName_t.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        fName_t.setToolTipText("WRITE YOUR FIRST NAME HERE");

        lName_t.setBackground(new java.awt.Color(252, 163, 17));
        lName_t.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        lName_t.setToolTipText("WRITE YOUR LAST NAME HERE");

        email_t.setBackground(new java.awt.Color(252, 163, 17));
        email_t.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        email_t.setToolTipText("LIKE : abc123@future.com");

        fName_l.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        fName_l.setForeground(new java.awt.Color(20, 33, 61));
        fName_l.setText("First Name :");

        lName_l.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        lName_l.setForeground(new java.awt.Color(20, 33, 61));
        lName_l.setText("Last Name :");

        email_l.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        email_l.setForeground(new java.awt.Color(20, 33, 61));
        email_l.setText(" Email :");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(20, 33, 61));
        jLabel5.setText("Password :");

        submit_b.setBackground(new java.awt.Color(255, 255, 255));
        submit_b.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        submit_b.setText("Submit");
        submit_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_bActionPerformed(evt);
            }
        });

        password_t.setBackground(new java.awt.Color(252, 163, 17));
        password_t.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N

        emailError_l.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        emailError_l.setForeground(new java.awt.Color(230, 55, 69));

        fnameError_l.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        fnameError_l.setForeground(new java.awt.Color(230, 55, 69));

        lnameError_l.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        lnameError_l.setForeground(new java.awt.Color(230, 55, 69));

        passwordError_l.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        passwordError_l.setForeground(new java.awt.Color(230, 55, 69));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(email_l, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(fName_l))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(submit_b, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(signIn_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fnameError_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lnameError_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(passwordError_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(emailError_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fName_t)
                                    .addComponent(lName_t, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(email_t, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(password_t, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addComponent(lName_l, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(back_b, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signIn_l, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(fnameError_l, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fName_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fName_t, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(lnameError_l, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lName_l, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lName_t, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(emailError_l, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_t, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email_l))
                .addGap(21, 21, 21)
                .addComponent(passwordError_l, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_t, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(submit_b, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_bActionPerformed
        // assigning some values to strings
        fName = fName_t.getText();
        lName = lName_t.getText();
        Email = email_t.getText();
        Password = password_t.getText();
        
        // some condations for prevent errors for inputs
            
            try {
                //record values in database (gmails table)
                Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/emails" , "root" , "363831");
                Statement st = connection.createStatement();
                DatabaseMetaData dbm = connection.getMetaData();
                ResultSet tables = null;
                if (Email.length() != 0 && Email.contains("@future.com") && fName.length() != 0 && lName.length() != 0 && Password.length() != 0) {
                    String user = Email.substring(0, Email.indexOf('@'));
                    tables = dbm.getTables(null, null, user, null);
                    if (!tables.next() || user.equals("")) {
                        // create a table for this user for record send emails
                        st.executeUpdate("CREATE TABLE " + user + "(subject VARCHAR(40),message VARCHAR(1000),sender VARCHAR(255),date VARCHAR(255),read_unread VARCHAR(20))");
                        // create a table for sented_user in sql
                        st.executeUpdate("CREATE TABLE sented_" + user + "(subject VARCHAR(40),message VARCHAR(1000),sender VARCHAR(255),date VARCHAR(255))");
                        // create a table for important_user tbale in sql
                        st.executeUpdate("CREATE TABLE important_" + user + "(subject VARCHAR(40),message VARCHAR(1000),sender VARCHAR(255))");
                        // insert accounts in basic table in sql
                        st.executeUpdate("INSERT INTO gmails (name,family,email,password) VALUES ('" + fName + "','" + lName + "','" + Email + "','" + Password + "')");
                        //open signup frame and close signin frame
                        Signup su = new Signup();
                        su.setVisible(true);
                        dispose();
                    }
                    if (tables.next()){
                    emailError_l.setText("this email is already exists !");
                    }
                }
                String user = Email.substring(0, Email.indexOf('@'));
                ResultSet tables2 = dbm.getTables(null, null, user, null);
                // some condations for prevent errors for inputs
                if (Email.length() == 0) {
                    emailError_l.setText("enter an email !");
                }
                if (!Email.contains("@future.com")){
                    emailError_l.setText("enter @future.com !");
                }
                if (fName.length() == 0){
                    fnameError_l.setText("enter your name !");
                }
                if (lName.length() == 0) {
                    lnameError_l.setText("enter your last name !");
                }
                if (Password.length() == 0) {
                    passwordError_l.setText("enter a strong password !");
                }
                if (Email.contains("@future.com") && Email.length() != 0) {
                    emailError_l.setText("");
                }
                if(fName.length() != 0) {
                    fnameError_l.setText("");
                }
                if (lName.length() != 0) {
                    lnameError_l.setText("");
                }
                if (Password.length() != 0) {
                    passwordError_l.setText("");
                }
       
                
            } catch (SQLException ex) {
                Logger.getLogger(Signin.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_submit_bActionPerformed
// back to signup frame with flash button
    private void back_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_bActionPerformed
        Signup su = new Signup();
        su.setVisible(true);
        dispose();
    }//GEN-LAST:event_back_bActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatLightLaf.setup();

// create UI here...
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signin().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_b;
    private javax.swing.JLabel emailError_l;
    private javax.swing.JLabel email_l;
    private javax.swing.JTextField email_t;
    private javax.swing.JLabel fName_l;
    private javax.swing.JTextField fName_t;
    private javax.swing.JLabel fnameError_l;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lName_l;
    private javax.swing.JTextField lName_t;
    private javax.swing.JLabel lnameError_l;
    private javax.swing.JLabel passwordError_l;
    private javax.swing.JPasswordField password_t;
    private javax.swing.JLabel signIn_l;
    public static final javax.swing.JButton submit_b = new javax.swing.JButton();
    // End of variables declaration//GEN-END:variables
}
