/////////////////////////////////////////////////////////////////morteza mahdi zadeh
/////////////////////////////////////////////////////////////////4012023030
import com.mysql.cj.jdbc.Driver;
import java.sql.*;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    
    // make signupemail and pass !
    String signUpEmail;
    String signUpPassword;
    
    public Signup() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        signUp_l = new javax.swing.JLabel();
        email_t = new javax.swing.JTextField();
        email_l = new javax.swing.JLabel();
        password_l = new javax.swing.JLabel();
        signIn_b = new javax.swing.JButton();
        signUp_b = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        invalid_l = new javax.swing.JLabel();
        password_t = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 580));

        jPanel2.setBackground(new java.awt.Color(229, 229, 229));

        signUp_l.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        signUp_l.setForeground(new java.awt.Color(20, 33, 61));
        signUp_l.setText("SIGN IN");

        email_t.setBackground(new java.awt.Color(252, 163, 17));
        email_t.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        email_t.setToolTipText("WRITE YOUR EMAIL NAME");
        email_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_tActionPerformed(evt);
            }
        });

        email_l.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        email_l.setForeground(new java.awt.Color(20, 33, 61));
        email_l.setText("Email :");

        password_l.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        password_l.setForeground(new java.awt.Color(20, 33, 61));
        password_l.setText("password :");

        signIn_b.setBackground(new java.awt.Color(255, 255, 255));
        signIn_b.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        signIn_b.setText("Sign In");
        signIn_b.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        signIn_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signIn_bActionPerformed(evt);
            }
        });

        signUp_b.setBackground(new java.awt.Color(255, 255, 255));
        signUp_b.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        signUp_b.setText("Sign Up");
        signUp_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUp_bActionPerformed(evt);
            }
        });

        invalid_l.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        invalid_l.setForeground(new java.awt.Color(230, 55, 69));

        password_t.setBackground(new java.awt.Color(252, 163, 17));
        password_t.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(email_l)
                    .addComponent(password_l))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email_t, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_t, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invalid_l, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(signUp_b, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(signIn_b, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(signUp_l)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(signUp_l, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(invalid_l, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(email_t, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email_l))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password_t, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password_l))
                .addGap(18, 18, 18)
                .addComponent(signIn_b, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signUp_b, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Notebook\\OneDrive\\Documents\\NetBeansProjects\\Gmail\\gmail.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void email_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_tActionPerformed
        
    }//GEN-LAST:event_email_tActionPerformed

    private void signIn_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signIn_bActionPerformed
        // take email and pass from user
        signUpEmail = email_t.getText();
        signUpPassword = password_t.getText();
        // condation for prevent errors
        if (signUpEmail.length() == 0 || signUpPassword.length() == 0) {
            invalid_l.setText("invalid email or password !");
        }
        else 
        {
            try {
                // take records (email and pass) from database
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/emails" , "root" , "363831");
                Statement st = c.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM gmails WHERE email LIKE '" + signUpEmail + "' AND password LIKE '" + signUpPassword + "'" );
                if (rs.next()) {
                    // open inbox frame and close signup frame
                    Inbox I = new Inbox(signUpEmail);
                    I.setVisible(true);
                    dispose();
                }
                else {
                    invalid_l.setText("invalid email or password !");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_signIn_bActionPerformed
// open signin frame with signUp button
    private void signUp_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUp_bActionPerformed
        Signin si = new Signin();
        si.setVisible(true);
        dispose();
    }//GEN-LAST:event_signUp_bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatLightLaf.setup();

// create UI here...
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel email_l;
    private javax.swing.JTextField email_t;
    private javax.swing.JLabel invalid_l;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel password_l;
    private javax.swing.JPasswordField password_t;
    private javax.swing.JButton signIn_b;
    private javax.swing.JButton signUp_b;
    private javax.swing.JLabel signUp_l;
    // End of variables declaration//GEN-END:variables
}
